### PR TITLE
feat: update user-id method

### PR DESCRIPTION
**Pull request by ubrmnsh**

### CODE REVIEW

**Comment by ubrmnsh** [comment]
WIP...

**Comment by zhenghaoz** [comment]
I think you could reuse the modify user API rather than open a new one. For example, add a new field for the new user ID.

**Comment by zhenghaoz** [comment]
You have to rename feedbacks in the feedback table as well. All caches for this user will be invalid then.

**Comment by ubrmnsh** [comment]
hmm, I need to ask few more questions as we have some different use cases
which I am trying to implement, can I contact you through any other means
like email or something else?

thanks .

**Comment by zhenghaoz** [comment]
You can contact me in Discord. However, I am not always online. Just leave messages to me.

**Pull request closed without merging**
